<?php

use Illuminate\Database\Seeder;
use App\Feed;
use App\Marketplace;

class FeedMm extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $mp = Marketplace::create(['name' => 'MatahariMall', 'slug' => 'mataharimall' ]);
    	
        $input = array(
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.mataharimall.com/p-2/handphone?sort=created_time&order=desc'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.mataharimall.com/p-5/tablet?sort=created_time&order=desc'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.mataharimall.com/p-8/phablet-aksesoris?sort=created_time&order=desc'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.mataharimall.com/p-15/aksesoris-handphone?sort=created_time&order=desc'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.mataharimall.com/p-26/aksesoris-tablet?sort=created_time&order=desc'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.mataharimall.com/p-31/baterai-charger?sort=created_time&order=desc'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.mataharimall.com/p-36/modem?sort=created_time&order=desc'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.mataharimall.com/p-39/telepon-rumah-kantor?sort=created_time&order=desc'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.mataharimall.com/p-5335/wearable-device?sort=created_time&order=desc'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.mataharimall.com/p-534/jam-tangan-pria?sort=created_time&order=desc'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.mataharimall.com/p-541/jam-tangan-wanita?sort=created_time&order=desc'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.mataharimall.com/p-548/jam-tangan-anak?sort=created_time&order=desc'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.mataharimall.com/p-551/perhiasan?sort=created_time&order=desc'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.mataharimall.com/p-1291/tas-anak-anak?sort=created_time&order=desc'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.mataharimall.com/p-1300/aksesoris?sort=created_time&order=desc'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.mataharimall.com/p-2234/koper?sort=created_time&order=desc'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.mataharimall.com/p-1267/tas-wanita?sort=created_time&order=desc'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.mataharimall.com/p-1279/tas-pria?sort=created_time&order=desc'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.mataharimall.com/p-1309/peralatan-olahraga?sort=created_time&order=desc'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.mataharimall.com/p-1425/aksesoris-olahraga?sort=created_time&order=desc'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.mataharimall.com/p-1433/hobi?sort=created_time&order=desc'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.mataharimall.com/p-44/tv-video?sort=created_time&order=desc'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.mataharimall.com/p-69/audio?sort=created_time&order=desc'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.mataharimall.com/p-97/peralatan-elektronik?sort=created_time&order=desc'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.mataharimall.com/p-101/video-game?sort=created_time&order=desc'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.mataharimall.com/p-1032/perawatan-rumah?sort=created_time&order=desc'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.mataharimall.com/p-807/perlengkapan-dapur-dan-ruang-makan?sort=created_time&order=desc'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.mataharimall.com/p-906/perlengkapan-kamar-tidur?sort=created_time&order=desc'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.mataharimall.com/p-936/peralatan-mandi-handuk?sort=created_time&order=desc'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.mataharimall.com/p-971/dekorasi-rumah?sort=created_time&order=desc'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.mataharimall.com/p-1236/taman?sort=created_time&order=desc'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.mataharimall.com/p-1238/perlengkapan-hewan-peliharaan?sort=created_time&order=desc'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.mataharimall.com/p-1263/hadiah-suvenir?sort=created_time&order=desc'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.mataharimall.com/p-755/furnitur?sort=created_time&order=desc'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.mataharimall.com/p-4792/seasonal?sort=created_time&order=desc'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.mataharimall.com/p-562/dapur?sort=created_time&order=desc'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.mataharimall.com/p-629/pendingin-pemanas-ruangan?sort=created_time&order=desc'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.mataharimall.com/p-660/pembersih-rumah?sort=created_time&order=desc'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.mataharimall.com/p-677/perawatan-pakaian?sort=created_time&order=desc'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.mataharimall.com/p-329/kamera-slr?sort=created_time&order=desc'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.mataharimall.com/p-331/kamera-mirrorless?sort=created_time&order=desc'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.mataharimall.com/p-333/kamera-prosumer?sort=created_time&order=desc'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.mataharimall.com/p-335/kamera-pocket?sort=created_time&order=desc'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.mataharimall.com/p-337/kamera-instan?sort=created_time&order=desc'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.mataharimall.com/p-339/kamera-mini?sort=created_time&order=desc'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.mataharimall.com/p-341/kamera-video?sort=created_time&order=desc'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.mataharimall.com/p-345/aksesoris-kamera-kamera-video?sort=created_time&order=desc'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.mataharimall.com/p-358/kecantikan?sort=created_time&order=desc'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.mataharimall.com/p-478/alat-kesehatan-dan-kecantikan?sort=created_time&order=desc'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.mataharimall.com/p-501/kesehatan?sort=created_time&order=desc'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.mataharimall.com/p-1651/mobil?sort=created_time&order=desc'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.mataharimall.com/p-1679/gps?sort=created_time&order=desc'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.mataharimall.com/p-1683/motor-atv?sort=created_time&order=desc'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.mataharimall.com/p-1689/oli-pelumas?sort=created_time&order=desc'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.mataharimall.com/p-1691/cat-bodi-trim?sort=created_time&order=desc'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.mataharimall.com/p-1693/suku-cadang-performa-aksesoris?sort=created_time&order=desc'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.mataharimall.com/p-1701/peralatan-perlengkapan?sort=created_time&order=desc'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.mataharimall.com/p-1708/roda-ban?sort=created_time&order=desc'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.mataharimall.com/p-1717/kendaraan-lainnya?sort=created_time&order=desc'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.mataharimall.com/p-689/laptop?sort=created_time&order=desc'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.mataharimall.com/p-696/komputer-desktop?sort=created_time&order=desc'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.mataharimall.com/p-702/komponen-komputer?sort=created_time&order=desc'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.mataharimall.com/p-712/aksesoris-komputer-dan-laptop?sort=created_time&order=desc'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.mataharimall.com/p-724/komponen-jaringan?sort=created_time&order=desc'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.mataharimall.com/p-730/printer-tinta-printer?sort=created_time&order=desc'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.mataharimall.com/p-738/proyektor?sort=created_time&order=desc'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.mataharimall.com/p-742/scanner?sort=created_time&order=desc'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.mataharimall.com/p-744/penyimpanan-data?sort=created_time&order=desc'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.mataharimall.com/p-749/software?sort=created_time&order=desc'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.mataharimall.com/p-1925/non-food?sort=created_time&order=desc'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.mataharimall.com/p-1949/dairy-frozen?sort=created_time&order=desc'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.mataharimall.com/p-1730/makanan?sort=created_time&order=desc'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.mataharimall.com/p-1752/minuman?sort=created_time&order=desc'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.mataharimall.com/p-1622/aksesoris-anak-laki-laki?sort=created_time&order=desc'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.mataharimall.com/p-1628/aksesoris-anak-perempuan?sort=created_time&order=desc'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.mataharimall.com/p-1635/sepatu-anak-laki-laki?sort=created_time&order=desc'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.mataharimall.com/p-1642/sepatu-anak-perempuan?sort=created_time&order=desc'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.mataharimall.com/p-1464/pakaian-dalam-pakaian-tidur-anak-perempuan?sort=created_time&order=desc'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.mataharimall.com/p-1467/pakaian-anak-laki-laki?sort=created_time&order=desc'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.mataharimall.com/p-1476/pakaian-dalam-pakaian-tidur-anak-laki-laki?sort=created_time&order=desc'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.mataharimall.com/p-1479/mainan?sort=created_time&order=desc'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.mataharimall.com/p-1514/pakaian-anak-perempuan?sort=created_time&order=desc'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.mataharimall.com/p-1523/bayi?sort=created_time&order=desc'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.mataharimall.com/p-4237/kostum-anak?sort=created_time&order=desc'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.mataharimall.com/p-1802/instrumen-musik?sort=created_time&order=desc'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.mataharimall.com/p-1815/cd-dvd-film?sort=created_time&order=desc'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.mataharimall.com/p-1825/office-school-supplies?sort=created_time&order=desc'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.mataharimall.com/p-2151/cd-dvd-music?sort=created_time&order=desc'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.mataharimall.com/p-2163/buku-impor?sort=created_time&order=desc'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.mataharimall.com/p-1762/buku-lokal?sort=created_time&order=desc'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.mataharimall.com/p-1790/majalah?sort=created_time&order=desc'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.mataharimall.com/p-1995/shopping-restaurants?sort=created_time&order=desc'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.mataharimall.com/p-1999/beauty-spa?sort=created_time&order=desc'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.mataharimall.com/p-2002/health-fitness?sort=created_time&order=desc'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.mataharimall.com/p-2010/lifestyle?sort=created_time&order=desc'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.mataharimall.com/p-2017/educations?sort=created_time&order=desc'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.mataharimall.com/p-2023/fun-park?sort=created_time&order=desc'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.mataharimall.com/p-2027/entertainment?sort=created_time&order=desc'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.mataharimall.com/p-2038/pre-paid?sort=created_time&order=desc'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.mataharimall.com/p-2045/travel?sort=created_time&order=desc'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.mataharimall.com/p-2053/other-services?sort=created_time&order=desc'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://fashion.mataharimall.com/p-276/atasan?sort=created_time&order=desc'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://fashion.mataharimall.com/p-286/bawahan?sort=created_time&order=desc'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://fashion.mataharimall.com/p-312/sepatu-pria?sort=created_time&order=desc'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://fashion.mataharimall.com/p-292/sports?sort=created_time&order=desc'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://fashion.mataharimall.com/p-283/jeans?sort=created_time&order=desc'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://fashion.mataharimall.com/p-289/batik?sort=created_time&order=desc'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://fashion.mataharimall.com/p-322/kacamata?sort=created_time&order=desc'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://fashion.mataharimall.com/p-302/aksesoris?sort=created_time&order=desc'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://fashion.mataharimall.com/p-295/busana-muslim?sort=created_time&order=desc'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://fashion.mataharimall.com/p-2995/pakaian-dalam?sort=created_time&order=desc'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://fashion.mataharimall.com/p-2999/baju-tidur?sort=created_time&order=desc'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://fashion.mataharimall.com/p-4233/kostum-pria?sort=created_time&order=desc'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://fashion.mataharimall.com/p-202/atasan?sort=created_time&order=desc'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://fashion.mataharimall.com/p-196/dress?sort=created_time&order=desc'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://fashion.mataharimall.com/p-216/bawahan?sort=created_time&order=desc'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://fashion.mataharimall.com/p-230/overall?sort=created_time&order=desc'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://fashion.mataharimall.com/p-256/sepatu?sort=created_time&order=desc'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://fashion.mataharimall.com/p-212/jeans?sort=created_time&order=desc'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://fashion.mataharimall.com/p-225/sports?sort=created_time&order=desc'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://fashion.mataharimall.com/p-221/batik?sort=created_time&order=desc'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://fashion.mataharimall.com/p-269/kacamata?sort=created_time&order=desc'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://fashion.mataharimall.com/p-241/aksesoris?sort=created_time&order=desc'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://fashion.mataharimall.com/p-232/baju-muslim?sort=created_time&order=desc'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://fashion.mataharimall.com/p-228/pakaian-ibu-hamil?sort=created_time&order=desc'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://fashion.mataharimall.com/p-3002/pakaian-dalam?sort=created_time&order=desc'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://fashion.mataharimall.com/p-3008/baju-tidur?sort=created_time&order=desc'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://fashion.mataharimall.com/p-4230/kostum-wanita?sort=created_time&order=desc')
		);

		Feed::insert($input);			
    }
}
