<?php

use Illuminate\Database\Seeder;
use App\Feed;
use App\Marketplace;

class FeedBb extends Seeder
{

    public function run()
    {
    	$mp = Marketplace::create(['name' => 'Blibli', 'slug' => 'blibli' ]);
    	
        $input = array(
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.blibli.com/tablet/54593?o=1'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.blibli.com/wearable-gadget/54593?o=1'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.blibli.com/handphone/54593?o=1'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.blibli.com/aksesoris-handphone-tablet/54593?o=1'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.blibli.com/fitness/OL-1000001?o=1'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.blibli.com/lari/OL-1000001?o=1'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.blibli.com/olahraga-air/OL-1000001?o=1'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.blibli.com/golf/OL-1000001?o=1'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.blibli.com/olahraga-lainnya/OL-1000001?o=1'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.blibli.com/badminton/OL-1000001?o=1'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.blibli.com/sepakbola/OL-1000001?o=1'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.blibli.com/olahraga-sepeda/OL-1000001?o=1'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.blibli.com/skate/OL-1000001?o=1'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.blibli.com/warehouse-sale-sport/OL-1000001?o=1'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.blibli.com/hiking-camping/OL-1000001?o=1'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.blibli.com/tennis/OL-1000001?o=1'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.blibli.com/basketballs/OL-1000001?o=1'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.blibli.com/yoga-pilates/OL-1000001?o=1'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.blibli.com/bela-diri/OL-1000001?o=1'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.blibli.com/multimedia/53270?o=1'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.blibli.com/printer-refill/53270?o=1'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.blibli.com/media-penyimpanan/53270?o=1'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.blibli.com/intel-store/53270?o=1'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.blibli.com/facsimile-refill/53270?o=1'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.blibli.com/peralatan-gaming/53270?o=1'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.blibli.com/komputer/53270?o=1'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.blibli.com/perlengkapan-kantor/53270?o=1'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.blibli.com/scanner/53270?o=1'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.blibli.com/aksesoris-komputer/53270?o=1'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.blibli.com/aksesoris-kamera-digital/53184?o=1'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.blibli.com/flash-kamera/53184?o=1'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.blibli.com/kamera-digital/53184?o=1'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.blibli.com/baterai-kamera/53184?o=1'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.blibli.com/tas-case/53184?o=1'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.blibli.com/lensa-kamera/53184?o=1'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.blibli.com/kamera-video/53184?o=1'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.blibli.com/video-games/MA-1000001?o=1'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.blibli.com/permainan-luar-ruang/MA-1000001?o=1'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.blibli.com/building-sets-blocks/MA-1000001?o=1'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.blibli.com/action-figures/MA-1000001?o=1'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.blibli.com/games-puzzles/MA-1000001?o=1'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.blibli.com/model-kit/MA-1000001?o=1'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.blibli.com/permainan-edukasi/MA-1000001?o=1'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.blibli.com/bikes-scooters-ride-ons/MA-1000001?o=1'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.blibli.com/specialty-toys/MA-1000001?o=1'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.blibli.com/die-cast-r-c/MA-1000001?o=1'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.blibli.com/aneka-boneka/MA-1000001?o=1'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.blibli.com/peralatan-seni-kerajinan/MA-1000001?o=1'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.blibli.com/coffee-maker/54650?o=1'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.blibli.com/perlengkapan-elektronik-dapur/54650?o=1'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.blibli.com/pemanas-air/54650?o=1'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.blibli.com/pompa/54650?o=1'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.blibli.com/mesin-cuci-pengering/54650?o=1'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.blibli.com/video/54650?o=1'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.blibli.com/televisi/54650?o=1'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.blibli.com/dishwasher-sterilizer/54650?o=1'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.blibli.com/microwave-dan-oven/54650?o=1'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.blibli.com/pendingin-ruangan/54650?o=1'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.blibli.com/home-appliances/54650?o=1'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.blibli.com/kulkas-chiller-freezer/54650?o=1'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.blibli.com/perangkat-kecantikan/54650?o=1'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.blibli.com/elektronik-dapur/54650?o=1'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.blibli.com/cooker-cooker-hood/54650?o=1'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.blibli.com/security-cctv/54650?o=1'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.blibli.com/penghisap-debu/54650?o=1'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.blibli.com/audio/54650?o=1'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.blibli.com/baju-atasan-kasual-pria/54817?o=1'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.blibli.com/sepatu-sandal-pria/54817?o=1'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.blibli.com/aksesoris-pria/54817?o=1'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.blibli.com/muslim-kategori-pria/54817?o=1'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.blibli.com/international-brand/54817?o=1'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.blibli.com/bawahan-pria/54817?o=1'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.blibli.com/baju-atasan-formal-pria/54817?o=1'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.blibli.com/baju-luaran-pria/54817?o=1'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.blibli.com/pakaian-dalam-tidur-pria/54817?o=1'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.blibli.com/local-brand/54817?o=1'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.blibli.com/tas-dompet-pria/54817?o=1'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.blibli.com/jam-tangan-pria/54817?o=1'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.blibli.com/baju-batik-etnik-pria/54817?o=1'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.blibli.com/perlengkapan-ruang-makan/HO-1000001?o=1'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.blibli.com/perkakas-rumah-tangga/HO-1000001?o=1'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.blibli.com/jam/HO-1000001?o=1'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.blibli.com/furniture-kantor/HO-1000001?o=1'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.blibli.com/furniture-perlengkapan-bayi/HO-1000001?o=1'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.blibli.com/dekorasi/HO-1000001?o=1'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.blibli.com/travelling/HO-1000001?o=1'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.blibli.com/perlengkapan-dapur/HO-1000001?o=1'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.blibli.com/peralatan-taman-luar-ruang/HO-1000001?o=1'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.blibli.com/hobby-interest/HO-1000001?o=1'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.blibli.com/furniture-kamar-tidur/HO-1000001?o=1'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.blibli.com/buku/HO-1000001?o=1'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.blibli.com/perlengkapan-kamar-mandi/HO-1000001?o=1'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.blibli.com/stationery/HO-1000001?o=1'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.blibli.com/perlengkapan-perawatan-rumah-tangga/HO-1000001?o=1'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.blibli.com/majalah/HO-1000001?o=1'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.blibli.com/furniture-ruang-makan-dapur/HO-1000001?o=1'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.blibli.com/furniture-anak/HO-1000001?o=1'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.blibli.com/furniture-ruang-keluarga/HO-1000001?o=1'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.blibli.com/perlengkapan-kamar-tidur/HO-1000001?o=1'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.blibli.com/aksesoris-fashion-wanita/54912?o=1'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.blibli.com/pakaian-wanita/54912?o=1'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.blibli.com/jam-tangan-wanita/54912?o=1'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.blibli.com/tas-wanita/54912?o=1'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.blibli.com/muslim-kategori-wanita/54912?o=1'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.blibli.com/sepatu-sandal-wanita/54912?o=1'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.blibli.com/perlengkapan-makan-bayi/55076?o=1'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.blibli.com/perlengkapan-pesta/55076?o=1'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.blibli.com/sepatu-anak/55076?o=1'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.blibli.com/perlengkapan-tidur-bayi/55076?o=1'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.blibli.com/peralatan-mandi-perawatan-kulit-bayi/55076?o=1'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.blibli.com/pakaian-anak-perempuan/55076?o=1'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.blibli.com/ibu-hamil-menyusui/55076?o=1'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.blibli.com/jam-tangan-anak/55076?o=1'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.blibli.com/branded-outlet-ibu-anak/55076?o=1'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.blibli.com/kaos-kaki-anak-bayi/55076?o=1'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.blibli.com/perlengkapan-makan-anak/55076?o=1'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.blibli.com/parcel-hadiah/55076?o=1'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.blibli.com/pakaian-anak-laki-laki/55076?o=1'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.blibli.com/aksesoris-anak/55076?o=1'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.blibli.com/babysitter/55076?o=1'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.blibli.com/nutrisi-susu-formula-makanan-bayi/55076?o=1'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.blibli.com/popok-bayi/55076?o=1'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.blibli.com/perlengkapan-bayi/55076?o=1'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.blibli.com/pakaian-bayi/55076?o=1'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.blibli.com/keamanan-bayi-dan-balita/55076?o=1'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.blibli.com/jasa-perawatan/TI-1000001?o=1'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.blibli.com/pertunjukan-aktivitas/TI-1000001?o=1'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.blibli.com/pendidikan/TI-1000001?o=1'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.blibli.com/tiket-seminar/TI-1000001?o=1'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.blibli.com/voucher-kesehatan-kecantikan/TI-1000001?o=1'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.blibli.com/kuliner-rumah-tangga/TI-1000001?o=1'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.blibli.com/paket-wisata-internasional/TI-1000001?o=1'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.blibli.com/tiket-perjalanan/TI-1000001?o=1'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.blibli.com/sport-fitness/TI-1000001?o=1'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.blibli.com/pelatihan/TI-1000001?o=1'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.blibli.com/paket-wisata-domestik/TI-1000001?o=1'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.blibli.com/tiket-pertunjukan/TI-1000001?o=1'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.blibli.com/perawatan-pria/53203?o=1'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.blibli.com/farmasi-suplemen-kesehatan/53203?o=1'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.blibli.com/alat-penata-rambut/53203?o=1'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.blibli.com/perawatan-wajah/53203?o=1'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.blibli.com/pengharum-parfum/53203?o=1'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.blibli.com/salon-profesional-spa/53203?o=1'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.blibli.com/perawatan-rambut/53203?o=1'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.blibli.com/make-up/53203?o=1'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.blibli.com/peralatan-medis/53203?o=1'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.blibli.com/kutek-perawatan-kuku/53203?o=1'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.blibli.com/perawatan-tubuh/53203?o=1'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.blibli.com/peralatan-kendaraan/53704?o=1'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.blibli.com/fashion-otomotif/53704?o=1'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.blibli.com/perawatan-kendaraan/53704?o=1'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.blibli.com/suku-cadang-mobil/53704?o=1'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.blibli.com/suku-cadang-motor-orisinil/53704?o=1'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.blibli.com/interior-mobil/53704?o=1'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.blibli.com/keamanan-berkendara/53704?o=1'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.blibli.com/audio-video-mobil/53704?o=1'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.blibli.com/otomotif-mobil/53704?o=1'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.blibli.com/suku-cadang-motor/53704?o=1'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.blibli.com/eksterior-mobil/53704?o=1'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.blibli.com/asuransi-kendaraan/53704?o=1'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.blibli.com/suku-cadang-mobil-orisinil/53704?o=1'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.blibli.com/aksesoris-motor/53704?o=1'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.blibli.com/motor/53704?o=1'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.blibli.com/beras-pasta-makanan-instan/53400?o=1'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.blibli.com/minyak-saus-bumbu-masak/53400?o=1'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.blibli.com/makanan-organik/53400?o=1'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.blibli.com/baking-tepung-kue/53400?o=1'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.blibli.com/minuman-kuliner/53400?o=1'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.blibli.com/roti-cereal/53400?o=1'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.blibli.com/permen-coklat/53400?o=1'),
			array( 'marketplace_id' => $mp->id, 'url' => 'https://www.blibli.com/snacks-makanan-kering/53400?o=1')
		);

		Feed::insert($input);
    }
}